---
title: "Report"
output: 
  html_document:
    theme: flatly
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## <u>Motivation</u> 

Our project goals were to analyze Google Trends data for the 2018 midterm elections. We chose to focus on Texas because of the close race between Beto O’Rourke and Ted Cruz. We wanted to identify the most highly searched political topics and examine different geographic components, such as where certain searches occurred. Our motivation is that this is a currently relevant issue in the U.S. and allows for analyses of civic engagement among American voters. 

## <u>Related Work </u> 

We were inspired to explore this research question due to the high amount of media coverage on the close race between O’Rourke and Cruz. Click [here](http://www.wbur.org/npr/654059869/beto-orourke-ted-cruz-texas-senate) and [here](https://www.vox.com/2018/9/12/17841716/ted-cruz-beto-orourke-senate-midterm) for some articles reported before the midterm election.

A blog website that focuses on using statistical analysis to model poll predictions revealed that they believe O’Rourke might have a chance at winning the race against Ted Cruz. They explained the factors that were looked at in their model predictions [here](https://fivethirtyeight.com/features/election-update-why-our-model-thinks-beto-orourke-really-has-a-chance-in-texas/)


## <u>Initial Questions</u>

- How does voter registration for this election compare to previous year’s? Due to the close race between O’Rourke and Cruz, will this increase voter registration? 
- What are the most highly searched political topics and how do they vary by county or district?
- How do political topic searches differ by party (Democrat vs Republican)? 

Over the course of the project, we realized that we only had Google Trends data from September to November 2018, which limited our ability to look at Trend data over time. Consequently, we restricted our analyses to this year’s data, specifically September 2018, and we did not compare 2018 data to that of previous years.

## <u>Data </u>

- Refer to our Data Source Tab for a detailed description of our data sources
- We downloaded CSV files from Google Trends Datastore for data on the top searched issues by US Congressional District
- We scraped election results data from a New York Times article that reported on the midterm elections.
- Most searched topics analyses  

##### **Top 5 Most Searched Topics**
- We determined the top five most searched topics related to the election using Google Trends data for search interests. Looking at the “Top searched issues by US Congressional District” dataset, we extracted the Texas districts and the search counts of all searched topics across districts. These counts ranged from 0 to 100 based on the topic’s proportion to all searches on all topics.  
- According to Google, these values were generated by dividing each data point by the total searches of the geography and time range it represents to compare relative popularity.  
- We summed up the search counts for each topic for all the Texas districts and found these topics to have the highest search frequencies: healthcare, immigration, medicaid, medicare, and september 11 attack.  
- We then filtered to include only these five topics to use on our analyses 

##### **Top 5 Most Populated Districts**   
Using https://www.census.gov/mycd/, we found the top 5 most populated districts in Texas to be: Districts 22, 26, 3, 8, 31
We then filtered to include these five districts in our analyses   

##### **Most Democrat vs Republican Districts** 
Using https://www.cookpolitical.com/index.php/pvi-map-and-district-list, we decided to use the Cook Partisan Voting Index (PVI) as a measure for how Democrat or Republican each district is. The most Democratic districts were 9, 30, 18, and 33. The most Republican districts were 13, 11, 8, and 4. 
We then filtered to include only these 8 districts in our analyses
We also created a “party” variable to label whether a specific district is Democrat or Republican 

## <u>Exploratory Analysis </u> 

- We created an interactive map of Texas to show voting results by county
- First, we created a bar graph of total votes for each party candidate and found that there were significantly less votes for Dikeman
- Moving forward, we narrowed our results to Ted Cruz and Beto O’Rourke

## <u>Additional Analysis </u>

####**Linear Regression**  
Using a merged dataset with the searched topics and vote results, we ran linear regressions to examine the linear relationship between all searched topics and the number of votes for the two different candidates across counties and districts in Texas
We wanted to examine if there was a relationship between the searched topics (health care, immigration, medicaid, medicare, and September 11 attacks) and actual vote results for the candidates. 
In our models, we used the variable for candidates’ poll counts as our continuous outcome, and one of the five searched topics as our predictor. We ran the models individually with one searched topic at a time. 
Below is the r-code for our statistical test analysis: 

####**Fisher’s Exact Test**  
We used a Fisher’s exact test to examine the relationship between topics searched and political party. A Fisher’s Exact Test was ran as opposed to a standard Chi-Squared Tests as some of the cells in our dataset were below the expected count.
We wanted to examine if the topics (health care, immigration, medicaid, medicare, September 11 attacks) were related to which political party the counties voted for. 
All counties were pooled together.
Our p-value was 0.1008 which was not statistically significant.
Below is the r-code for our statistical test analysis:


## <u>Discussion </u>