---
title: "texas_interactive_map"
author: "Amadeia Rector"
date: "11/29/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tigris)
library(rvest)
library(leaflet)
library(dplyr)
library(tidyverse)

```

```{r scraping election results for texas from the web table method}

url = "https://www.nytimes.com/elections/results/texas-senate"
nytimes_data = read_html(url, col_types = "ccdd")

nytimes_data

```

```{r extracting tables from website}
nytimes_data %>% 
  html_nodes(css = "table")

```

```{r making 2nd web table into another tibble}

table_county =  (nytimes_data %>% html_nodes(css = "table")) %>% 
  .[[2]] %>%
  html_table() %>% 
  slice(1:(n() - 1)) %>% 
  select(-Rpt.) %>% 
  janitor::clean_names()

```

## Tidying county table

```{r loading dataset}
#remove the commas in the numbers first
table_county$cruz <- gsub(",","",table_county$cruz)
table_county$o_rourke <- gsub(",","",table_county$o_rourke)
table_county$dikeman <- gsub(",","",table_county$dikeman)

table_county = 
  table_county %>% 
  mutate(cruz = as.numeric(cruz), o_rourke = as.numeric(o_rourke), dikeman = as.numeric(dikeman))

table_county$county = str_replace(table_county$county,"La Vaca", "Lavaca")
table_county$county = str_replace(table_county$county,"De Witt", "DeWitt")
#county names misspelled (was causing issues with merging later on)
table_county_long = gather(table_county, key = candidate, value = votes, cruz:dikeman)
```
```{r}
for_GIS= table_county %>%
  mutate(cruz_orour_rat = cruz/o_rourke,
         status = as.numeric(cruz_orour_rat>=1),
         winner = ifelse(status==1, "Ted Cruz", "Beto O'Rourke"))
```

Cleaning data so as to merge with GIS...
```{r}
texas_counties = counties(state = "48",year = "2017") #Texas fips code is 48, using most recent census data, 2017

tx_midterms = geo_join(texas_counties, for_GIS, "NAME", "county")
```

```{r}
pal = colorFactor(c("blue", "red"), tx_midterms$status)

popup = paste(sep = "<br/>",
              paste0("<b>Winner: </b>", tx_midterms$winner),
              paste0("<b>County: </b>", tx_midterms$county),
              paste0("<b>Votes for Ted Cruz: </b>", tx_midterms$cruz),
              paste0("<b>Votes for Beto O'Rourke: </b>", tx_midterms$o_rourke),
              paste0("<b>Votes for Neal Dikeman: </b>", tx_midterms$dikeman))
```

```{r}
leaflet(tx_midterms) %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addPolygons(fillColor= ~pal(status),
              color = "black",
              popup = popup,
              fillOpacity = 0.5,
              weight = 0.5) %>% 
  addLegend(position = "bottomleft",
            colors = c("blue", "red"),
            labels = c("Democrat", "Republican"),
            opacity = 1,
            title = "2018 Texas Senate Election Results")
```






